#!/bin/bash
cd "$(dirname "$0")"
. common/libc.sh

#ubuntu_versions=(
#    xenial
#    bionic
#    eoan
#    focal
#)

#for version in ${ubuntu_versions[@]}; do
#    get_current_ubuntu $version amd64 libc6
#    get_current_ubuntu $version amd64 libc6-i386
#    get_current_ubuntu $version i386 libc6
#done

get_all_ubuntu archive-eglibc https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/e/eglibc/
get_all_ubuntu archive-glibc https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/
get_all_ubuntu archive-old-eglibc https://mirrors.aliyun.com/oldubuntu-releases/ubuntu/pool/main/e/eglibc/
get_all_ubuntu archive-old-glibc https://mirrors.nju.edu.cn/ubuntu-old-releases/ubuntu/pool/main/g/glibc/

#debian_versions=(
#    jessie
#    stretch
#    buster
#    bullseye
#)
#for version in ${debian_versions[@]}; do
#  get_current_debian $version i386 libc6
#  get_current_debian $version amd64 libc6
#  get_current_debian $version amd64 libc6-i386
#done
